# Miscellaneous https://www.authelia.com/configuration/miscellaneous/introduction/
# Set also AUTHELIA_JWT_SECRET_FILE
theme: auto

# First Factor https://www.authelia.com/configuration/first-factor/file/
authentication_backend:
  file:
    path: /run/secrets/users_database.yml

# Second Factor https://www.authelia.com/configuration/second-factor/introduction/
totp:
  issuer: ullrich.is

# Security https://www.authelia.com/configuration/security/access-control/
access_control:
  default_policy: deny
  rules:
    - domain: '*.ullrich.is'
      policy: 'two_factor'

# Session https://www.authelia.com/configuration/session/introduction/
# Set also AUTHELIA_SESSION_SECRET_FILE
session:
  cookies:
    - name: 'authelia_session'
      domain: 'ullrich.is'
      authelia_url: 'https://auth.ullrich.is'
      default_redirection_url: 'https://flame.ullrich.is'
      expiration: '1 hour'
      inactivity: '5 minutes'

  # https://www.authelia.com/configuration/session/redis/
  # Set also AUTHELIA_SESSION_REDIS_PASSWORD_FILE if appropriate
  redis:
    host: redis
    port: 6379

# Storage https://www.authelia.com/configuration/storage/postgres/
# Set also AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE
# Set also AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
storage:
  postgres:
    address: tcp://database:5432
    database: authelia
    username: authelia

# SMTP Notifier https://www.authelia.com/configuration/notifications/smtp/
# Set also AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
notifier:
  smtp:
    address: smtp.fastmail.com:587
    username: ullrich@ullrich.is
    sender: "Authelia <no-reply@ullrich.is>"

# https://www.authelia.com/configuration/telemetry/metrics/
telemetry:
  metrics:
    enabled: true
    address: 'tcp://:9959/metrics'
    buffers:
      read: 4096
      write: 4096
    timeouts:
      read: '6s'
      write: '6s'
      idle: '30s'
