#
# Hetzner Online GmbH - installimage
#
# This file contains the configuration used to install this
# system via installimage script. Comments have been removed.
#
# More information about the installimage script and
# automatic installations can be found in our wiki:
#
# http://wiki.hetzner.de/index.php/Installimage
#

DRIVE1 /dev/sda
DRIVE2 /dev/sdb
SWRAID 1
SWRAIDLEVEL 1
BOOTLOADER grub
HOSTNAME Ubuntu-1810-cosmic-64-minimal
PART /boot  ext3     512M
PART lvm    vg0       all
LV vg0   root   /        ext4        2048G
LV vg0   swap   swap     swap          16G
LV vg0   tmp    /tmp     ext4          10G
LV vg0   home   /home    ext4          all
IMAGE /root/.oldroot/nfs/install/../images/Ubuntu-1810-cosmic-64-minimal.tar.gz
