global:
  scrape_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: caddy
    static_configs:
      - targets: ["caddy:2018"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "iptables-exporter"
    static_configs:
      - targets: ["iptables-exporter:9119"]
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: authelia
    static_configs:
      - targets: ["authelia:9959"]
  - job_name: github-metrics
    static_configs:
      - targets: ["github-traffic:8001"]
