### Hetzner Online GmbH installimage
network:
  version: 2
  renderer: networkd
  ethernets:
    enp4s0:
      addresses:
        - 176.9.150.227/32
        - 2a01:4f8:160:33c7::2/64
      routes:
        - on-link: true
          to: 0.0.0.0/0
          via: 176.9.150.225
      gateway6: fe80::1
      nameservers:
        addresses:
          - 213.133.100.100
          - 213.133.98.98
          - 213.133.99.99
          - 2a01:4f8:0:1::add:9898
          - 2a01:4f8:0:1::add:1010
          - 2a01:4f8:0:1::add:9999
