services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    networks:
      - caddy
      - prometheus
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    labels:
      caddy: cadvisor.ullrich.is
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.import: secure *
      flame.type: application
      flame.name: cadvisor
      flame.url: https://cadvisor.ullrich.is

networks:
  caddy:
    external: true
  prometheus:
    external: true
